### ISSUE TITLE
ext is missing in Source + error in Source::setFd validator

### ISSUE THREAD

**Issue by QuentinGallard** [visavi/openrtb#2]
Hi,

in [OpenRTB Specification 2.5](https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf), the object `Source` can have an `ext` attribute.

Also in the object `Source`, the validator in setFd use the var `$allimps` instead of `$fd`

Can you add it ?
Here is a PR to fix it : https://github.com/visavi/openrtb/pull/1 .

**Comment by visavi** [comment]
Thanks, added

**Comment by QuentinGallard** [comment]
Thank you for the merge and the tag :+1:
